flags: {}
extra-package-dbs: []
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3
extra-deps:
- StateVar-1.1.0.4
- adjunctions-4.3
- base-orphans-0.5.4
- bifunctors-5.3
- comonad-5
- contravariant-1.4
- cpphs-1.20.1
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dependent-map-0.2.1.0
- dependent-sum-0.3.2.1
- dependent-sum-template-0.0.0.4
- distributive-0.5.0.2
- exception-transformers-0.4.0.4
- exceptions-0.8.2.1
- free-4.12.4
- ghcjs-dom-0.2.3.1
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.13
- kan-extensions-5.0.1
- lens-4.13.2.1
- polyparse-1.12
- prelude-extras-0.4.0.3
- profunctors-5.2
- ref-tf-0.4
- reflection-2.1.2
- reflex-0.4.0
- reflex-dom-0.3
- safe-0.3.9
- semigroupoids-5.0.1
- semigroups-0.18.1
- tagged-0.8.3
- th-expand-syns-0.4.0.0
- th-extras-0.0.0.2
- th-lift-0.7.6
- th-orphans-0.13.0
- th-reify-many-0.1.4
- these-0.6.2.1
- transformers-compat-0.5.1.4
- void-0.7.1
compiler-check: match-exact
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
resolver: ghcjs-0.2.0.20160414_ghc-7.10.3
